<?php

namespace App\Console\Commands;

use App\Client;
use App\Comparison;
use App\ClientInvoices;
use App\GuestList;
use App\Hotel;
use App\Invoices;
use App\InvoicesTours;
use App\Offices;
use App\Quotation;
use App\Status;
use App\Tour;
use App\TourDay;
use App\TourPackage;
use App\Transaction;
use App\User;
use Carbon\Carbon;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * Builds a fully populated tour for manual testing — frontsheet,
 * services, quotation, guest list, supplier + client invoice, billing.
 * Idempotent against repeated runs: delete the previous test tour
 * (matched by name) before creating a new one.
 *
 *   php artisan seed:test-tour
 */
class SeedTestTour extends Command
{
    protected $signature   = 'seed:test-tour {--name=EetsTravel Test Tour}';
    protected $description = 'Create a fully populated tour (services + quotation + guest list + invoices + transactions) for manual testing';

    public function handle(): int
    {
        $name = (string) $this->option('name');

        // Anchors — first existing user/client/office/hotel. The seeder
        // doesn't pretend to create those; we just attach to whatever is
        // already in the DB so the tour wires up to real records.
        $user   = User::first();
        $client = Client::first();
        $office = Offices::first();
        $hotel  = Hotel::first();
        if (!$user || !$client || !$office || !$hotel) {
            $this->error('Need at least one User, Client, Office, and Hotel in the DB before seeding. Aborting.');
            return self::FAILURE;
        }

        // Resolve statuses by name+type so this works regardless of
        // numeric id reshuffling.
        $tourStatusGo      = Status::where(['type' => 'tour',            'name' => 'Go Ahead'])->value('id');
        $packageStatusConf = Status::where(['type' => 'service_in_tour', 'name' => 'Confirmed'])->value('id');

        DB::transaction(function () use ($name, $user, $client, $office, $hotel, $tourStatusGo, $packageStatusConf) {

            // Idempotency: blow away any prior test tour with this name.
            Tour::where('name', $name)->get()->each(function ($t) {
                $dayIds = TourDay::where('tour', $t->id)->pluck('id');
                $pkgIds = DB::table('packages_tour_days')->whereIn('tour_day_id', $dayIds)->pluck('tour_package_id');
                DB::table('packages_tour_days')->whereIn('tour_day_id', $dayIds)->delete();
                TourPackage::whereIn('id', $pkgIds)->delete();
                TourDay::where('tour', $t->id)->delete();
                Quotation::where('tour_id', $t->id)->get()->each(function ($q) {
                    Comparison::where('id', $q->id)->delete();
                    $q->delete();
                });
                GuestList::where('tour_id', $t->id)->delete();
                $clientInvoices = ClientInvoices::where('tour_id', $t->id)->pluck('id');
                DB::table('invoice_items')->whereIn('invoice_id', $clientInvoices)->delete();
                Transaction::whereIn('invoice_id', $clientInvoices)->delete();
                ClientInvoices::whereIn('id', $clientInvoices)->delete();
                // Supplier invoices link via the InvoicesTours pivot.
                $supplierInvoiceIds = InvoicesTours::where('invoices_tours_id', $t->id)->pluck('invoices_id');
                InvoicesTours::where('invoices_tours_id', $t->id)->delete();
                Invoices::whereIn('id', $supplierInvoiceIds)->delete();
                $t->forceDelete();
            });

            // -- Tour -----------------------------------------------
            $departure  = Carbon::today()->addDays(14);
            $retirement = (clone $departure)->addDays(4);

            $tour = new Tour();
            $tour->name           = $name;
            $tour->overview       = 'Seeded tour for manual testing — covers hotel, restaurant, event, guide, transfer.';
            $tour->remark         = 'Generated by `php artisan seed:test-tour`.';
            $tour->departure_date = $departure->format('Y-m-d');
            $tour->retirement_date= $retirement->format('Y-m-d');
            $tour->pax            = 25;
            $tour->pax_free       = 2;
            $tour->rooms          = 13;
            $tour->country_begin  = 'DE';
            $tour->city_begin     = 'Berlin';
            $tour->country_end    = 'AT';
            $tour->city_end       = 'Vienna';
            $tour->status         = $tourStatusGo ?: 4;
            $tour->author         = $user->id;
            $tour->assigned_user  = $user->id;
            $tour->client_id      = $client->id;
            $tour->responsible    = 'Operations Desk';
            $tour->phone          = '+49 30 0000 0000';
            $tour->itinerary_tl   = 'Test Tour Leader';
            $tour->external_name  = 'TEST-' . strtoupper(Str::random(6));
            // The landing page is publicly viewable iff ?t=<share_token>
            // matches. Generate a token so the user can open the landing
            // page without being logged in.
            $tour->share_token    = Str::random(40);
            $tour->total_amount   = 18500;
            $tour->price_for_one  = 740;
            $tour->save();
            // Mirror the assigned user into the pivot so user-scoped lookups work.
            $tour->users()->syncWithoutDetaching([$user->id]);

            // -- TourDays + Packages on each day ---------------------
            // service types from TourPackageController::$serviceTypes
            //   0 hotel · 1 event · 2 guide · 3 transfer · 4 restaurant
            $dayPlan = [
                0 => [
                    ['type' => 3, 'name' => 'Airport pickup → Berlin hotel', 'time_from' => '09:00:00', 'time_to' => '10:30:00', 'total' => 220],
                    ['type' => 0, 'name' => $hotel->name . ' (Berlin)',       'time_from' => '15:00:00', 'time_to' => '23:59:00', 'total' => 3200],
                    ['type' => 4, 'name' => 'Welcome dinner — Brauhaus',     'time_from' => '19:30:00', 'time_to' => '22:00:00', 'total' => 480],
                ],
                1 => [
                    ['type' => 2, 'name' => 'City walking tour with guide',   'time_from' => '09:30:00', 'time_to' => '12:30:00', 'total' => 300],
                    ['type' => 1, 'name' => 'Museum entry — Pergamon',         'time_from' => '14:00:00', 'time_to' => '16:30:00', 'total' => 350],
                    ['type' => 0, 'name' => $hotel->name . ' (Berlin)',       'time_from' => '15:00:00', 'time_to' => '23:59:00', 'total' => 3200],
                ],
                2 => [
                    ['type' => 3, 'name' => 'Coach transfer Berlin → Prague', 'time_from' => '08:00:00', 'time_to' => '14:00:00', 'total' => 950],
                    ['type' => 0, 'name' => 'Hotel Praha Centro',              'time_from' => '15:00:00', 'time_to' => '23:59:00', 'total' => 2900],
                    ['type' => 4, 'name' => 'Group dinner — Old Town',        'time_from' => '19:00:00', 'time_to' => '21:30:00', 'total' => 520],
                ],
                3 => [
                    ['type' => 2, 'name' => 'Prague Castle guided visit',     'time_from' => '10:00:00', 'time_to' => '13:00:00', 'total' => 340],
                    ['type' => 0, 'name' => 'Hotel Praha Centro',              'time_from' => '15:00:00', 'time_to' => '23:59:00', 'total' => 2900],
                ],
                4 => [
                    ['type' => 3, 'name' => 'Transfer Prague → Vienna airport','time_from' => '07:00:00', 'time_to' => '13:00:00', 'total' => 1100],
                ],
            ];

            foreach ($dayPlan as $dayIndex => $packages) {
                // TourDay has no $fillable or $guarded set, so Laravel
                // treats every column as guarded against mass assignment.
                // Direct property assignment bypasses that.
                $day = new TourDay();
                $day->date = (clone $departure)->addDays($dayIndex)->format('Y-m-d');
                $day->tour = $tour->id;
                $day->save();
                $this->line("    [day {$dayIndex}] id={$day->id} date={$day->date}");

                foreach ($packages as $p) {
                    $pkg = new TourPackage();
                    $pkg->name         = $p['name'];
                    $pkg->description  = $p['name'];
                    $pkg->status       = $packageStatusConf ?: 9;
                    $pkg->paid         = 0;
                    $pkg->pax          = 25;
                    $pkg->pax_free     = 2;
                    $pkg->total_amount = $p['total'];
                    $pkg->currency     = 'EUR';
                    $pkg->time_from    = $p['time_from'];
                    $pkg->time_to      = $p['time_to'];
                    $pkg->rate         = '';
                    $pkg->note         = '';
                    $pkg->type         = $p['type'];
                    $pkg->reference    = 'TEST-' . Str::upper(Str::random(5));
                    $pkg->tour_id      = $tour->id;
                    $pkg->itn          = 1;  // include in itinerary
                    $pkg->vch          = 1;  // include in voucher
                    $pkg->save();

                    DB::table('packages_tour_days')->insert([
                        'tour_package_id' => $pkg->id,
                        'tour_day_id'     => $day->id,
                    ]);
                }
            }

            // -- Quotation + Comparison (Front sheet) -------------------
            $quotation = new Quotation();
            $quotation->name      = $tour->name . ' — Quotation v1';
            $quotation->note      = 'Initial quotation for the test tour.';
            $quotation->rate      = 1;
            $quotation->tour_id   = $tour->id;
            $quotation->mark_up   = 15;
            $quotation->user_id   = $user->id;
            $quotation->is_confirm= 1;
            $quotation->save();

            // Comparison.id == Quotation.id is the 1:1 join key used by the
            // front-sheet route (/comparison/{quotation_id}). The status
            // columns are DATE typed, not boolean — null means "not yet",
            // a date means "marked done on that day".
            // updateOrCreate so we overwrite any orphaned comparison that may
            // already exist at this id from a prior partial run.
            $today = Carbon::today()->format('Y-m-d');
            Comparison::updateOrCreate(
                ['id' => $quotation->id],
                [
                    'hotel_list_sent'        => $today,
                    'front_sheet_sent'       => null,
                    'visa_confirmation_sent' => null,
                    'group_fix'              => null,
                    'rooming_list_received'  => null,
                    'final_documents_sent'   => null,
                    'comments'               => 'Awaiting front-sheet sign-off.',
                ]
            );

            // -- Guest list -----------------------------------------
            $guestRoster = [
                ['name' => 'Alex Morgan',        'passport' => 'DE12345678'],
                ['name' => 'Beatrice Lindholm',  'passport' => 'SE98765432'],
                ['name' => 'Carlos Mendoza',     'passport' => 'ES44556677'],
                ['name' => 'Dana Whitfield',     'passport' => 'GB11223344'],
            ];
            $guestList = new GuestList();
            $guestList->tour_id   = $tour->id;
            $guestList->name      = $tour->name . ' — guests';
            $guestList->version   = 1;
            $guestList->content   = json_encode($guestRoster);
            $guestList->author_id = $user->id;
            $guestList->hotel_ids = json_encode([$hotel->id]);
            $guestList->save();

            // -- Client invoice + items + partial payment ----------
            // ClientInvoices guards office_id/tour_id/client_id/invoice_no;
            // use direct property assignment so the FKs land correctly.
            $clientInvoice = new ClientInvoices();
            $clientInvoice->invoice_no         = 'CI-' . strtoupper(Str::random(6));
            $clientInvoice->date               = $departure->format('Y-m-d');
            $clientInvoice->currency           = 'EUR';
            $clientInvoice->office_id          = $office->id;
            $clientInvoice->tour_id            = $tour->id;
            $clientInvoice->client_id          = $client->id;
            $clientInvoice->extra_cost         = 0;
            $clientInvoice->note               = 'Test client invoice.';
            $clientInvoice->amount_receiveable = 18500.00;
            $clientInvoice->save();
            DB::table('invoice_items')->insert([
                ['item_name' => 'Tour package — base price', 'quantity' => 25, 'vat' => 7,  'amount' => 600.00, 'total_amount' => 16050.00, 'invoice_id' => $clientInvoice->id],
                ['item_name' => 'Single-room supplement',    'quantity' => 5,  'vat' => 7,  'amount' => 200.00, 'total_amount' => 1070.00,  'invoice_id' => $clientInvoice->id],
                ['item_name' => 'Excursion uplift',           'quantity' => 1,  'vat' => 19, 'amount' => 1290.00,'total_amount' => 1535.10,  'invoice_id' => $clientInvoice->id],
            ]);
            Transaction::create([
                'invoice_id'     => $clientInvoice->id,
                'date'           => $departure->copy()->subDays(3)->format('Y-m-d'),
                'payment_method' => 'Bank transfer',
                'pay_to'         => 'Client',
                'trans_no'       => 'TR-' . strtoupper(Str::random(5)),
                'amount'         => 9000.00,  // partial — leaves 9500 outstanding
            ]);

            // -- Supplier invoice + tour link + payment ------------
            // Invoices guards office_id + invoice_no; direct assignment.
            $supplierInvoice = new Invoices();
            $supplierInvoice->office_id    = $office->id;
            $supplierInvoice->dueDate      = $departure->copy()->addDays(30)->format('Y-m-d');
            $supplierInvoice->receivedDate = $departure->format('Y-m-d');
            $supplierInvoice->invoice_no   = 'SI-' . strtoupper(Str::random(6));
            $supplierInvoice->total_amount = 8500.00;
            $supplierInvoice->extra_amount = 0;
            $supplierInvoice->note         = 'Test supplier invoice (hotel + transfers).';
            $supplierInvoice->save();
            InvoicesTours::create([
                'invoices_id'        => $supplierInvoice->id,
                'invoices_tours_id'  => $tour->id,
                'package_id'         => 0,
            ]);
            Transaction::create([
                'invoice_id'     => $supplierInvoice->id,
                'date'           => $departure->copy()->subDays(1)->format('Y-m-d'),
                'payment_method' => 'Bank transfer',
                'pay_to'         => 'Supplier',
                'trans_no'       => 'TR-' . strtoupper(Str::random(5)),
                'amount'         => 4250.00,  // half paid
            ]);

            // Verify the day count survived end-of-transaction.
            $finalDays = TourDay::where('tour', $tour->id)->count();
            $this->line("  end-of-seed day count: {$finalDays}");
            $this->info("Seeded tour id={$tour->id} name=\"{$tour->name}\"");
            $this->line('');
            $this->line('Browse the seeded data:');
            $base = config('app.url') ?: 'http://localhost';
            $this->line("  Tour overview     : {$base}/tour/{$tour->id}");
            $this->line("  Tour edit         : {$base}/tour/{$tour->id}/edit");
            $this->line("  Landing page      : {$base}/tour/{$tour->id}/landingpage?t={$tour->share_token}");
            $this->line("  Quotation edit    : {$base}/quotation/{$quotation->id}/edit");
            $this->line("  Front sheet       : {$base}/comparison/{$quotation->id}");
            $this->line("  Client invoice    : {$base}/accounting/{$tour->id}");
            $this->line("  Itinerary PDF     : {$base}/tour/{$tour->id}/export/short");
            $this->line("  Voucher PDF       : {$base}/tour/{$tour->id}/export/voucher");
            $this->line("  Hotels PDF        : {$base}/tour/{$tour->id}/export/hotel");
            $this->line("  Itinerary HTML    : {$base}/tour/{$tour->id}/export/html");
            $this->line('');
            $this->line("Tour leader name  : {$tour->itinerary_tl}");
            $this->line("Share token       : {$tour->share_token}");
        });

        return self::SUCCESS;
    }
}
