<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\ValidationException;

class SnappyMailController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('preventBackHistory');
    }

    /**
     * Single sign-on into SnappyMail using the logged-in user's saved email credentials.
     *
     * The hash is generated by SnappyMail itself (\RainLoop\Api::CreateUserSsoHash),
     * which stores the email/password pair in its own cache. SnappyMail's /?sso&hash=...
     * endpoint then consumes that cache entry to log the user in. The hash is single-use
     * and only valid for ~10 seconds, so we redirect immediately.
     */
    public function sso(Request $request)
    {
        /** @var User $user */
        $user = Auth::user();

        if (empty($user->email_login)) {
            return redirect()->route('snappymail.configure')
                ->with('warning', 'Please configure your mailbox credentials before opening webmail.');
        }

        $password = $this->getEmailPassword($user);
        if ($password === null) {
            return redirect()->route('snappymail.configure')
                ->with('error', 'Your saved mailbox password could not be read. Please re-enter it.');
        }

        try {
            $hash = $this->createSnappyMailSsoHash($user->email_login, $password);
        } catch (\Throwable $e) {
            Log::error('SnappyMail SSO bootstrap failed', [
                'user_id' => $user->id,
                'error'   => $e->getMessage(),
            ]);
            return redirect('/home')->with('error', 'Webmail is unavailable right now. Please try again.');
        }

        if (empty($hash)) {
            Log::error('SnappyMail SSO hash creation returned empty', ['user_id' => $user->id]);
            return redirect('/home')->with('error', 'Webmail login failed. Please try again.');
        }

        $base = rtrim(config('snappymail.url', '/mail'), '/');
        return redirect($base . '/?sso&hash=' . $hash);
    }

    /**
     * Direct link to SnappyMail (lets SnappyMail show its own login form).
     */
    public function direct()
    {
        return redirect(config('snappymail.url', '/mail'));
    }

    /**
     * Admin panel access (Spatie role check).
     */
    public function admin()
    {
        if (!Auth::user()->hasRole('admin')) {
            return redirect()->back()->with('error', 'Admin access required');
        }
        return redirect(config('snappymail.admin_url', '/mail/?admin'));
    }

    /**
     * Render the per-user mailbox configuration form.
     */
    public function configure()
    {
        return view('snappymail.configure', [
            'user'           => Auth::user(),
            'imapHost'       => env('IMAP_HOST', ''),
            'imapPort'       => env('IMAP_PORT', 993),
            'imapEncryption' => env('IMAP_ENCRYPTION', 'ssl'),
        ]);
    }

    /**
     * Save the user's mailbox credentials (password is encrypted at rest).
     */
    public function saveConfiguration(Request $request)
    {
        $data = $request->validate([
            'email_login'    => 'required|email',
            'email_password' => 'required|string|min:1',
        ]);

        /** @var User $user */
        $user = Auth::user();
        $user->email_login = $data['email_login'];
        $user->email_password = Crypt::encryptString($data['email_password']);
        $user->email_password_encrypted = true;
        $user->save();

        return redirect()->route('snappymail.sso')
            ->with('success', 'Mailbox configuration saved.');
    }

    /**
     * Lightweight status endpoint useful for debugging the integration.
     */
    public function status()
    {
        $bootstrap = $this->snappyMailBootstrapPath();

        return response()->json([
            'installed'      => is_file($bootstrap),
            'url'            => config('snappymail.url', '/mail'),
            'bootstrap_path' => $bootstrap,
            'user_configured' => !empty(Auth::user()->email_login),
        ]);
    }

    /**
     * Decrypt and return the user's mailbox password. Returns null on failure so the
     * caller can prompt the user to re-enter credentials.
     */
    private function getEmailPassword(User $user)
    {
        if (empty($user->email_password)) {
            return null;
        }

        if ($user->email_password_encrypted) {
            try {
                return Crypt::decryptString($user->email_password);
            } catch (\Throwable $e) {
                Log::error('Failed to decrypt email password', [
                    'user_id' => $user->id,
                    'error'   => $e->getMessage(),
                ]);
                return null;
            }
        }

        // Legacy plain-text rows from before the encrypted-at-rest column existed.
        return $user->email_password;
    }

    /**
     * Bootstrap SnappyMail in API mode and generate a real single-use SSO hash.
     *
     * SnappyMail's bootstrap defines its constants, autoloaders and cache provider,
     * then skips request handling because SNAPPYMAIL_INCLUDE_AS_API is set.
     */
    private function createSnappyMailSsoHash(string $email, string $password): ?string
    {
        $bootstrap = $this->snappyMailBootstrapPath();
        if (!is_file($bootstrap)) {
            throw new \RuntimeException("SnappyMail bootstrap not found at {$bootstrap}");
        }

        if (!class_exists(\RainLoop\Api::class, false)) {
            $_ENV['SNAPPYMAIL_INCLUDE_AS_API'] = true;
            require_once $bootstrap;
        }

        return \RainLoop\Api::CreateUserSsoHash($email, $password);
    }

    private function snappyMailBootstrapPath(): string
    {
        return config('snappymail.path', public_path('snappymail/index.php'));
    }
}
